name: spotify_clock
description: Spotify Clock App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  auto_size_text: ^3.0.0
  get:
  supabase_flutter: ^1.10.11
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

fonts:
  - family: IBM Plex Sans
    fonts:
      - asset: assets/fonts/IBMPlexSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/IBMPlexSans-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/IBMPlexSans-Light.ttf
        weight: 300
      - asset: assets/fonts/IBMPlexSans-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/IBMPlexSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/IBMPlexSans-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/IBMPlexSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/IBMPlexSans-REgularItalic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/IBMPlexSans-Thin.ttf
        weight: 100
      - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
        weight: 100
        style: italic
        
